INSERT INTO purchase_items (name, category, order_unit, count_unit, allows_decimal, min_stock, max_stock, origin, is_active, pending_review) VALUES 
('ESPETO CORAÇÃO C/5 UN', 'ESPETOS', 'un', 'un', false, 15, 30, 'cozinha_central', true, false),
('ESPETO DE BABY BEEF - 5UN', 'ESPETOS', 'un', 'un', false, 25, 80, 'cozinha_central', true, false),
('ESPETO FRANGO c/ 5 UN.', 'ESPETOS', 'un', 'un', false, 30, 75, 'cozinha_central', true, false),
('ESPETO KAFTA C/ QUEIJO c/ 5 UN.', 'ESPETOS', 'un', 'un', false, 10, 20, 'cozinha_central', true, false),
('ESPETO LINGUIÇA MINEIRA c/ 6 UN.', 'ESPETOS', 'un', 'un', false, 10, 18, 'cozinha_central', true, false),
('ESPETO MISTO c/ 5 UN.', 'ESPETOS', 'un', 'un', false, 5, 30, 'cozinha_central', true, false),
('ESPETO QUEIJO COALHO c/ 5 UN.', 'ESPETOS', 'un', 'un', false, 2, 16, 'cozinha_central', true, false),
('ESPETO SALSICHÃO c/ 5 UN.', 'ESPETOS', 'un', 'un', false, 5, 20, 'cozinha_central', true, false),
('ESPETO SUÍNO c/ 5 UN.', 'ESPETOS', 'un', 'un', false, 3, 15, 'cozinha_central', true, false),
('ESPETO VEGETARIANO c/ 1 UN.', 'ESPETOS', 'un', 'un', false, 2, 5, 'cozinha_central', true, false),
('QUEIJO COALHO FESTIVAL c/ 10UN', 'ESPETOS', 'un', 'un', false, 5, 10, 'cozinha_central', true, false),
('CHORIZO', 'PROTEÍNAS', 'un', 'un', false, 5, 10, 'cozinha_central', true, false),
('COSTELA', 'PROTEÍNAS', 'un', 'un', false, 7, 12, 'cozinha_central', true, false),
('COSTELINHA SUÍNA', 'PROTEÍNAS', 'un', 'un', false, 1, 3, 'cozinha_central', true, false),
('FILÉ MIGNON EXECUTIVO - 0,18KG', 'PROTEÍNAS', 'un', 'un', false, 66, 80, 'cozinha_central', true, false),
('FILÉ MIGNON REFEIÇÃO - 0,55KG 5 uni', 'PROTEÍNAS', 'un', 'un', false, 5, 14, 'cozinha_central', true, false),
('GALETO +/- 1KG', 'PROTEÍNAS', 'un', 'un', false, 50, 180, 'cozinha_central', true, false),
('HAMBÚRGUER BOV150g WESSEL 6,3kg CX42u', 'PROTEÍNAS', 'un', 'un', false, 25, 60, 'cozinha_central', true, false),
('PICANHA EXECUTIVO - 0,16KG', 'PROTEÍNAS', 'un', 'un', false, 5, 15, 'cozinha_central', true, false),
('PICANHA FATIADA - 0,65KG 5 uni', 'PROTEÍNAS', 'un', 'un', false, 5, 15, 'cozinha_central', true, false),
('TÁBUA CORAÇÃO DE ALCATRA - 0,25KG 3uni', 'PROTEÍNAS', 'un', 'un', false, 6, 10, 'cozinha_central', true, false),
('LINGUIÇA DE PERNIL PEQUENA C/10 UN', 'ENTRADAS', 'un', 'un', false, NULL, NULL, 'cozinha_central', true, true),
('LINGUIÇA PROVOLONE ROLO', 'ENTRADAS', 'un', 'un', false, 4, 1, 'cozinha_central', true, true),
('LINGUIÇA TOSCANA NABRASA 160GR- C/7 UN', 'ENTRADAS', 'un', 'un', false, 42, 10, 'cozinha_central', true, true),
('MEIO PÃO DE ALHO', 'ENTRADAS', 'un', 'un', false, 12, 4, 'cozinha_central', true, true),
('PALMITO', 'ENTRADAS', 'un', 'un', false, 3, 2, 'cozinha_central', true, true),
('PASTEL GRANDE CAMARÃO - 2UN', 'ENTRADAS', 'un', 'un', false, 16, 4, 'cozinha_central', true, true),
('PASTEL GRANDE CATUPIRY - 2UN', 'ENTRADAS', 'un', 'un', false, 16, 2, 'cozinha_central', true, true),
('PASTEL GRANDE COSTELA - 2UN', 'ENTRADAS', 'un', 'un', false, 10, 2, 'cozinha_central', true, true),
('PÃO DE ALHO', 'ENTRADAS', 'un', 'un', false, 24, 40, 'cozinha_central', true, false),
('BACON DEF TIRAS (HAMBÚRGUER) - 0,25KG', 'LANCHES', 'un', 'un', false, 2, 9, 'cozinha_central', true, false),
('MAIONESE TEMPERADA', 'LANCHES', 'un', 'un', false, 1, 3, 'cozinha_central', true, false),
('CEBOLA CARAMELIZADA SPICY', 'LANCHES', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('PÃO BRIOCHE TRAD HB 48UN GERG. MESCLADO', 'LANCHES', 'un', 'un', false, 31, 132, 'cozinha_central', true, false),
('QUEIJO CHEDDAR VIGOR MOLHO', 'LANCHES', 'un', 'un', false, 1, 3, 'cozinha_central', true, false),
('KETCHUP 1,033kg Heinz', 'LANCHES', 'un', 'un', false, 1, 3, 'cozinha_central', true, false),
('MOLHO AMERICANO ZAFRAN', 'LANCHES', 'un', 'un', false, 1, 3, 'cozinha_central', true, false),
('MOSTARDA 1,1KG JUNIOR', 'LANCHES', 'un', 'un', false, 1, 3, 'cozinha_central', true, false),
('MAIONESE DE BACON 1,1KG JUNIOR', 'LANCHES', 'un', 'un', false, 1, 3, 'cozinha_central', true, false),
('QUEIJO CHEDDAR FATIADO - 2,27KG 150 FATIAS', 'LANCHES', 'un', 'un', false, 40, 150, 'cozinha_central', true, false),
('QUEIJO PROC PRATO 2,24KG VIGOR 160 FATIAS', 'LANCHES', 'un', 'un', false, 40, 160, 'cozinha_central', true, false),
('PICKLES PEPINO RODELAS 440G HANKS', 'LANCHES', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('PUDIM DE LEITE', 'SOBREMESAS', 'un', 'un', false, 6, 14, 'cozinha_central', true, false),
('CONFIT PIMENTA BIQUINHO', 'COZINHA CENTRAL - MOLHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('MOLHO A CAMPANHA  - 2.3Kg', 'COZINHA CENTRAL - MOLHOS', 'un', 'un', false, 4, 8, 'cozinha_central', true, false),
('MOLHO GORGONZOLA - POTE 500ML', 'COZINHA CENTRAL - MOLHOS', 'un', 'un', false, 2, 5, 'cozinha_central', true, false),
('MOLHO PESTO POTE - 0,5L', 'COZINHA CENTRAL - MOLHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('ALHO TRITURADO', 'COZINHA CENTRAL - BASES', 'un', 'un', false, 4, 14, 'cozinha_central', true, false),
('CROUTONS', 'COZINHA CENTRAL - BASES', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('FAROFA 2,5 KG', 'COZINHA CENTRAL - BASES', 'un', 'un', false, 6, 14, 'cozinha_central', true, false),
('FARINHA CRUA 1KG', 'COZINHA CENTRAL - BASES', 'un', 'un', false, 2, 4, 'cozinha_central', true, false),
('FEIJÃO COZIDO - 3KG', 'COZINHA CENTRAL - BASES', 'un', 'un', false, 6, 18, 'cozinha_central', true, false),
('ALHO FRITO 1KG', 'COZINHA CENTRAL - BASES', 'un', 'un', false, 1, 3, 'cozinha_central', true, false),
('LEITE INTEGRAL', 'LATICÍNIOS E OVOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Margarina Vegetal 80% 14kg Elogiata', 'LATICÍNIOS E OVOS', 'un', 'un', false, 1, 1, 'cozinha_central', true, false),
('OVO BRANCO', 'LATICÍNIOS E OVOS', 'un', 'un', false, 30, 60, 'cozinha_central', true, false),
('QUEIJO PARMESÃO RALADO - 0,2KG', 'LATICÍNIOS E OVOS', 'un', 'un', false, 1, 4, 'cozinha_central', true, false),
('ARROZ AG  LF 5kg Máximo', 'MERCEARIA', 'un', 'un', false, 8, 12, 'cozinha_central', true, false),
('AÇÚCAR REFINADO', 'MERCEARIA', 'un', 'un', false, 1, 3, 'cozinha_central', true, false),
('SAL REFINADO', 'MERCEARIA', 'un', 'un', false, 16, 40, 'cozinha_central', true, false),
('OLEO DE ALGODÃO 14kg ELOGIATA', 'MERCEARIA', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('MATE LEÃO DA CASA 1KG', 'MERCEARIA', 'un', 'un', false, 2, 3, 'cozinha_central', true, false),
('BATATA CANOA 2,5kg MCCAIN', 'CONGELADOS', 'un', 'un', false, 6, 15, 'cozinha_central', true, false),
('BATATA PALITO NOBREDO 2KG', 'CONGELADOS', 'un', 'un', false, 10, 20, 'cozinha_central', true, false),
('MANDIOCA TOLETE MATHEUS 2,5', 'CONGELADOS', 'un', 'un', false, 6, 12, 'cozinha_central', true, false),
('ALECRIM', 'HORTIFRUTI', 'un', 'un', false, 1, 3, 'cozinha_central', true, false),
('ALFACE AMERICANA', 'HORTIFRUTI', 'un', 'un', false, 1, 3, 'cozinha_central', true, false),
('ALFACE CRESPA', 'HORTIFRUTI', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('BATATA ASTERIX', 'HORTIFRUTI', 'un', 'un', false, 10, 25, 'cozinha_central', true, false),
('BATATA CALABRESA', 'HORTIFRUTI', 'un', 'un', false, 6, 18, 'cozinha_central', true, false),
('BRÓCOLIS COMUM', 'HORTIFRUTI', 'un', 'un', false, 4, 8, 'cozinha_central', true, false),
('CEBOLA ROXA', 'HORTIFRUTI', 'un', 'un', false, 2, 4, 'cozinha_central', true, false),
('LARANJA SELETA', 'HORTIFRUTI', 'un', 'un', false, 10, 25, 'cozinha_central', true, false),
('LIMÃO', 'HORTIFRUTI', 'un', 'un', false, 8, 12, 'cozinha_central', true, false),
('LIMÃO SICILIANO', 'HORTIFRUTI', 'un', 'un', false, 1, 3, 'cozinha_central', true, false),
('SALSA CRESPA', 'HORTIFRUTI', 'un', 'un', false, 2, 2, 'cozinha_central', true, false),
('TOMATE SALADA', 'HORTIFRUTI', 'un', 'un', false, 4, 10, 'cozinha_central', true, false),
('TOMATE GRAPE', 'HORTIFRUTI', 'un', 'un', false, 2, 3, 'cozinha_central', true, false),
('RUCULA', 'HORTIFRUTI', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Azeite Composto 5,02L Lisboa Blend', 'CONDIMENTOS', 'un', 'un', false, 2, 5, 'cozinha_central', true, false),
('Azeitona Fatiada Preta 2kg WWL', 'CONDIMENTOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('MELADO - 0,5KG', 'CONDIMENTOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('MILHO TORRADO C/ MOSTARDA E MEL - 0,25KG', 'CONDIMENTOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('PIMENTA TABASCO', 'CONDIMENTOS', 'un', 'un', false, 1, 3, 'cozinha_central', true, false),
('AZEITE SALÃO', 'CONDIMENTOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('VINAGRE - 0,75L', 'CONDIMENTOS', 'un', 'un', false, 1, 3, 'cozinha_central', true, false),
('CHIMICHURRI - 0,2KG', 'TEMPEROS', 'un', 'un', false, 4, 10, 'cozinha_central', true, false),
('LEMON PEPPER - 0,4KG', 'TEMPEROS', 'un', 'un', false, 2, 5, 'cozinha_central', true, false),
('LOURO - 0,01KG', 'TEMPEROS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('SAL DE PARRILLA - PORÇÃO', 'TEMPEROS', 'un', 'un', false, 4, 8, 'cozinha_central', true, false),
('SAL TEMPERADO 200G', 'TEMPEROS', 'un', 'un', false, 2, 4, 'cozinha_central', true, false),
('Chopp Brahma Claro 50L Barril', 'BEBIDAS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Cerv Heineken Pils 12x473ml', 'BEBIDAS', 'un', 'un', false, 7, 36, 'cozinha_central', true, false),
('Cerv Heineken 0.0% LN 330ml', 'BEBIDAS', 'un', 'un', false, 7, 36, 'cozinha_central', true, false),
('Coca-Cola Zero Lata 350ml', 'BEBIDAS', 'un', 'un', false, 56, 96, 'cozinha_central', true, false),
('Coca-Cola Lata 350ml', 'BEBIDAS', 'un', 'un', false, 38, 96, 'cozinha_central', true, false),
('Coca-Cola Original PET 1,5L', 'BEBIDAS', 'un', 'un', false, 11, 28, 'cozinha_central', true, false),
('Coca-Cola zero PET 1,5L', 'BEBIDAS', 'un', 'un', false, 17, 43, 'cozinha_central', true, false),
('Dell Vale Uva Lata 290ml', 'BEBIDAS', 'un', 'un', false, 10, 18, 'cozinha_central', true, false),
('Dell Vale Pessego Lata 290ml', 'BEBIDAS', 'un', 'un', false, 10, 18, 'cozinha_central', true, false),
('Sprit Lata 350ml', 'BEBIDAS', 'un', 'un', false, 4, 12, 'cozinha_central', true, false),
('Fanta Uva Lata 350ml', 'BEBIDAS', 'un', 'un', false, 4, 18, 'cozinha_central', true, false),
('Fanta Laranja Lata 350ml', 'BEBIDAS', 'un', 'un', false, 2, 12, 'cozinha_central', true, false),
('Matte Leão Limão WF PET 300ml CX12', 'BEBIDAS', 'un', 'un', false, 12, 36, 'cozinha_central', true, false),
('Matte Leão Natural WF PET 300ml CX12', 'BEBIDAS', 'un', 'un', false, 12, 42, 'cozinha_central', true, false),
('Matte Leão Natural Zero WF PET 300ml', 'BEBIDAS', 'un', 'un', false, 12, 36, 'cozinha_central', true, false),
('Ice Tea Limão PET 300ml CX12', 'BEBIDAS', 'un', 'un', false, 6, 24, 'cozinha_central', true, false),
('Ice Tea Pêssego PET 300ml CX12', 'BEBIDAS', 'un', 'un', false, 6, 12, 'cozinha_central', true, false),
('Água c/ gás Cristal', 'BEBIDAS', 'un', 'un', false, 55, 22, 'cozinha_central', true, true),
('Água s/ gas Cristal', 'BEBIDAS', 'un', 'un', false, 55, 19, 'cozinha_central', true, true),
('Guaraná  Antarctica  Lata 350ml 12 unid', 'BEBIDAS', 'un', 'un', false, 24, 60, 'cozinha_central', true, false),
('Guaraná  Antarctica zero Lata 350ml 12 unid', 'BEBIDAS', 'un', 'un', false, 24, 48, 'cozinha_central', true, false),
('Guaraná Antarctica zero  1,5 6 unid', 'BEBIDAS', 'un', 'un', false, 12, 36, 'cozinha_central', true, false),
('Guaraná  Antarctica 1,5L 6 unid', 'BEBIDAS', 'un', 'un', false, 12, 36, 'cozinha_central', true, false),
('H2OH Limoneto C/Gás PET 500ml CX12', 'BEBIDAS', 'un', 'un', false, 12, 24, 'cozinha_central', true, false),
('H2OH Limão C/Gás PET 500ml CX12', 'BEBIDAS', 'un', 'un', false, 12, 24, 'cozinha_central', true, false),
('Red Bull Lata 250ml SixPack', 'BEBIDAS', 'un', 'un', false, 6, 12, 'cozinha_central', true, false),
('Hocus Pocus Orange Sunshine GFA 500ml CX6', 'BEBIDAS', 'un', 'un', false, 12, 24, 'cozinha_central', true, false),
('Hocus Pocus Magic 500 ml cx 6', 'BEBIDAS', 'un', 'un', false, 12, 18, 'cozinha_central', true, false),
('Stella Artois Long Neck 330ml SixPack SH4', 'BEBIDAS', 'un', 'un', false, 12, 24, 'cozinha_central', true, false),
('Stella Artois Pure Gold LN 330ml SP SH4', 'BEBIDAS', 'un', 'un', false, 18, 48, 'cozinha_central', true, false),
('Tônica Antarctica Lata 350ml SH12', 'BEBIDAS', 'un', 'un', false, 12, 24, 'cozinha_central', true, false),
('CAPSULA DE CAFÉ', 'BEBIDAS', 'un', 'un', false, 100, 300, 'cozinha_central', true, false),
('MALZIBIER BRAHMA lata 350ml c/12', 'BEBIDAS', 'un', 'un', false, 12, 24, 'cozinha_central', true, false),
('Absolut Original Garrafa 1L', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Aperol 750ml', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Zanella Merlot Vinho tinto 750ml', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Zanella Chardonnay Vinho branco 750ml', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Zanella Blanc de Blanc - Espumante 750ml', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Da quinta - Cachaça 500ml', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Werneck - Cachaça 750ml', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Smirnoff - Vodka 600ml', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Salinas imburana - Cachaça 1l', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Salinas Cristalina - Cachaça 1l', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Sagatiba - Cachaça 700ml', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Lua Nova - Cachaça 1l', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Charmosa de minas - Cachaça 980ml', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('51 - Cachaça 965lm', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Seleta - Cachaça 1l', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Licor 43 700ml', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Salton Brut 750ml', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('Surrender Vinho Cabernet Sauvignon/Merlot 3L', 'DESTILADOS E VINHOS', 'un', 'un', false, 1, 6, 'cozinha_central', true, false),
('CANUDO SHAKE IT´S  BIO  3000 - PCT 100', 'DESCARTÁVEIS', 'un', 'un', false, 100, 300, 'cozinha_central', true, false),
('EMBALAGEM DE ISOPOR CARNE - 100UN', 'DESCARTÁVEIS', 'un', 'un', false, 100, 200, 'cozinha_central', true, false),
('EMBALAGEM DE ISOPOR EXECUTIVO - 100UN', 'DESCARTÁVEIS', 'un', 'un', false, 100, 200, 'cozinha_central', true, false),
('EMBALAGEM  TAMPA EXECUTIVO - 100UN', 'DESCARTÁVEIS', 'un', 'un', false, 100, 200, 'cozinha_central', true, false),
('EMBALAGEM DE ISOPOR HAMBURG - 100UN', 'DESCARTÁVEIS', 'un', 'un', false, 100, 200, 'cozinha_central', true, false),
('GUARDANAPO SIMPLES', 'DESCARTÁVEIS', 'un', 'un', false, 200, 400, 'cozinha_central', true, false),
('JOGO AMERICANO 30X40 60G', 'DESCARTÁVEIS', 'un', 'un', false, 1, 3, 'cozinha_central', true, false),
('PAPEL ACOPLADO PERSON PCT1KG', 'DESCARTÁVEIS', 'un', 'un', false, 200, 1000, 'cozinha_central', true, false),
('POTE 30ML - 50UN', 'DESCARTÁVEIS', 'un', 'un', false, 100, 175, 'cozinha_central', true, false),
('POTE 60ML - 100UN', 'DESCARTÁVEIS', 'un', 'un', false, 100, 200, 'cozinha_central', true, false),
('POTE 145ML - 25UN', 'DESCARTÁVEIS', 'un', 'un', false, 100, 200, 'cozinha_central', true, false),
('POTE 250ML - 25UN', 'DESCARTÁVEIS', 'un', 'un', false, 150, 300, 'cozinha_central', true, false),
('POTE 500ML - 25UN', 'DESCARTÁVEIS', 'un', 'un', false, 150, 300, 'cozinha_central', true, false),
('QUENTINHA 500ML - 100UN', 'DESCARTÁVEIS', 'un', 'un', false, 100, 200, 'cozinha_central', true, false),
('QUENTINHA 1100ML - 100UN', 'DESCARTÁVEIS', 'un', 'un', false, 100, 200, 'cozinha_central', true, false),
('QUENTINHA 220ML - 100UN', 'DESCARTÁVEIS', 'un', 'un', false, 100, 200, 'cozinha_central', true, false),
('SACO DELIVERY (M) - 50UN', 'DESCARTÁVEIS', 'un', 'un', false, 150, 300, 'cozinha_central', true, false),
('SACO DELIVERY (G) - 50UN', 'DESCARTÁVEIS', 'un', 'un', false, 200, 400, 'cozinha_central', true, false),
('SACO DELIVERY (GG) - 50UN', 'DESCARTÁVEIS', 'un', 'un', false, 150, 300, 'cozinha_central', true, false),
('SACO EMBALAR TALHER PERSO - PCT 200', 'DESCARTÁVEIS', 'un', 'un', false, 200, 400, 'cozinha_central', true, false),
('SACOLA VERDE P - 110unid', 'DESCARTÁVEIS', 'un', 'un', false, 60, 110, 'cozinha_central', true, false),
('SACOLA BRANCA 100unid', 'DESCARTÁVEIS', 'un', 'un', false, 50, 200, 'cozinha_central', true, false),
('SALADEIRA 1000ML', 'DESCARTÁVEIS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('SALADEIRA 500ML', 'DESCARTÁVEIS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('FITA KRAFT', 'DESCARTÁVEIS', 'un', 'un', false, 4, 10, 'cozinha_central', true, false),
('ASSA RÁPIDO', 'DESCARTÁVEIS', 'un', 'un', false, 2, 3, 'cozinha_central', true, false),
('ETIQUETA VALIDADE 100UND', 'DESCARTÁVEIS', 'un', 'un', false, 150, 300, 'cozinha_central', true, false),
('TINTA ETIQUETADORA (PAPEL BRANCO)', 'DESCARTÁVEIS', 'un', 'un', false, 6, 10, 'cozinha_central', true, false),
('EMBALAGEM DE ESPETO 100UNI', 'DESCARTÁVEIS', 'un', 'un', false, 200, 400, 'cozinha_central', true, false),
('EMBALAGEM DE GALETO 400UNI', 'DESCARTÁVEIS', 'un', 'un', false, 200, 400, 'cozinha_central', true, false),
('TALHER DESCARTAVEL', 'DESCARTÁVEIS', 'un', 'un', false, 50, 100, 'cozinha_central', true, false),
('TOUCA DESCARTAVEL', 'DESCARTÁVEIS', 'un', 'un', false, 100, 200, 'cozinha_central', true, false),
('MEXEDOR DE CAFÉ', 'DESCARTÁVEIS', 'un', 'un', false, 50, 100, 'cozinha_central', true, false),
('GUARDANAPO PERSONALIZADO', 'DESCARTÁVEIS', 'un', 'un', false, 200, 400, 'cozinha_central', true, false),
('PAPEL ALUMINIO ROLO 45X65 MTS', 'DESCARTÁVEIS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('CANUDO DRINK', 'DESCARTÁVEIS', 'un', 'un', false, 50, 100, 'cozinha_central', true, false),
('BOBINA PICOTADA 16X30 ROLO', 'INSUMOS OPERACIONAIS', 'un', 'un', false, 2, 3, 'cozinha_central', true, false),
('BOBINA PICOTE 30X40 - ROLO MEDIA 1,71KG', 'INSUMOS OPERACIONAIS', 'un', 'un', false, 2, 3, 'cozinha_central', true, false),
('BOBINA PICOTE 40X60 - ROLO MEDIA 2,36KG', 'INSUMOS OPERACIONAIS', 'un', 'un', false, 2, 3, 'cozinha_central', true, false),
('BOBINA PICOTE 20X35 - ROLO MEDIA 1,71KG', 'INSUMOS OPERACIONAIS', 'un', 'un', false, 2, 3, 'cozinha_central', true, false),
('BOBINA TERMICA AMARELA 79X30 CX30- UNI', 'INSUMOS OPERACIONAIS', 'un', 'un', false, 4, 10, 'cozinha_central', true, false),
('SACHE AÇÚCAR UNIÃO 400 - PCT 100UND', 'INSUMOS OPERACIONAIS', 'un', 'un', false, 100, 300, 'cozinha_central', true, false),
('SACHE PALITO DENTAL 2000 - PCT100', 'INSUMOS OPERACIONAIS', 'un', 'un', false, 100, 300, 'cozinha_central', true, false),
('SACHE SAL ITA 2000 - PCT 100', 'INSUMOS OPERACIONAIS', 'un', 'un', false, 100, 300, 'cozinha_central', true, false),
('CARVAO - Un', 'INSUMOS OPERACIONAIS', 'un', 'un', false, 6, 14, 'cozinha_central', true, false),
('CLORIN VERDURAS', 'INSUMOS OPERACIONAIS', 'un', 'un', false, 2, 3, 'cozinha_central', true, false),
('BILHETINHO', 'INSUMOS OPERACIONAIS', 'un', 'un', false, 10, 20, 'cozinha_central', true, false),
('BISCOITO CAFÉ', 'INSUMOS OPERACIONAIS', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('FOLHA DE DESENHO', 'INSUMOS OPERACIONAIS', 'un', 'un', false, 10, 20, 'cozinha_central', true, false),
('ESPONJA DE AÇO', 'LIMPEZA', 'un', 'un', false, 2, 3, 'cozinha_central', true, false),
('DESINFETANTE LAVANDA -   5LT', 'LIMPEZA', 'un', 'un', false, 2, 4, 'cozinha_central', true, false),
('Detergente 500ml Neutro CX24', 'LIMPEZA', 'un', 'un', false, 12, 24, 'cozinha_central', true, false),
('ESPONJA 3M DUPLA FACE UND', 'LIMPEZA', 'un', 'un', false, 2, 4, 'cozinha_central', true, false),
('ESPONJA RISCA LIMPEZA (AZUL)', 'LIMPEZA', 'un', 'un', false, 3, 4, 'cozinha_central', true, false),
('ESPONJA FIBRACO 3M LIMPEZA PESADA Grande', 'LIMPEZA', 'un', 'un', false, 2, 4, 'cozinha_central', true, false),
('LUVA LIMPEZA UND', 'LIMPEZA', 'un', 'un', false, 1, 1, 'cozinha_central', true, false),
('ÁLCOOL LÍQUIDO - 70% 1L', 'LIMPEZA', 'un', 'un', false, 2, 5, 'cozinha_central', true, false),
('MASTER GRILL (ECOGRILL) - 1L', 'LIMPEZA', 'un', 'un', false, 2, 5, 'cozinha_central', true, false),
('PANO DE CHÃO GRANDE', 'LIMPEZA', 'un', 'un', false, 2, 5, 'cozinha_central', true, false),
('PERFEX AZUL ROLO 240M', 'LIMPEZA', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('SACO DE LIXO 200L', 'LIMPEZA', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('SACO DE LIXO 100L', 'LIMPEZA', 'un', 'un', false, 1, 2, 'cozinha_central', true, false),
('PAPEL TOALHA', 'LIMPEZA', 'un', 'un', false, 2, 5, 'cozinha_central', true, false),
('PAPEL FUNCIONARIO', 'LIMPEZA', 'un', 'un', false, 2, 4, 'cozinha_central', true, false),
('TOTAL', 'LIMPEZA', 'un', 'un', false, NULL, NULL, 'cozinha_central', true, true),
('ACÉM', 'FUNCIONÁRIO', 'kg', 'kg', true, NULL, NULL, 'cozinha_central', true, true),
('CARNE MOIDA', 'FUNCIONÁRIO', 'kg', 'kg', true, NULL, NULL, 'cozinha_central', true, true),
('BISTECA', 'FUNCIONÁRIO', 'kg', 'kg', true, NULL, NULL, 'cozinha_central', true, true),
('COXA COM SOBRECOXA', 'FUNCIONÁRIO', 'kg', 'kg', true, NULL, NULL, 'cozinha_central', true, true),
('FILE FRANGO', 'FUNCIONÁRIO', 'kg', 'kg', true, NULL, NULL, 'cozinha_central', true, true),
('DRUMETE', 'FUNCIONÁRIO', 'kg', 'kg', true, NULL, NULL, 'cozinha_central', true, true),
('PEIXE', 'FUNCIONÁRIO', 'kg', 'kg', true, NULL, NULL, 'cozinha_central', true, true),
('MACARRÃO', 'FUNCIONÁRIO', 'kg', 'kg', true, NULL, NULL, 'cozinha_central', true, true),
('LINGUIÇA', 'FUNCIONÁRIO', 'kg', 'kg', true, NULL, NULL, 'cozinha_central', true, true),
('SOBREPALETA', 'FUNCIONÁRIO', 'kg', 'kg', true, NULL, NULL, 'cozinha_central', true, true),
('VERDURA', 'FUNCIONÁRIO', 'kg', 'kg', true, NULL, NULL, 'cozinha_central', true, true),
('LEGUME', 'FUNCIONÁRIO', 'kg', 'kg', true, NULL, NULL, 'cozinha_central', true, true),
('AÇUCAR', 'FUNCIONÁRIO', 'kg', 'kg', true, NULL, NULL, 'cozinha_central', true, true),
('CAFÉ KG', 'FUNCIONÁRIO', 'kg', 'kg', true, NULL, NULL, 'cozinha_central', true, true);